#!/bin/sh -e

# Reinstall dependencies if package-lock.json changed

packageLockChanged=$(\
  git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD \
    | grep -c "package-lock.json" \
)

if [ "$packageLockChanged" != "0" ]; then
  npm ci --progress=false
fi
