#!/bin/bash -e

# Guard for branch naming convention

branchName=$(git rev-parse --abbrev-ref HEAD)
branchNameRegExp="^((main|next)|(feat|fix|docs|refactor|test)\/[a-z0-9-]+)$"

if [[ ! $branchName =~ $branchNameRegExp ]]; then
  echo -e "\n\e[31mError\e[0m: \e[1mInvalid branch name\e[0m\n"
  echo -e "You are trying to commit to a branch named \e[31m\"$branchName\"\e[0m.\n"
  echo -e "Branch names in this project must adhere to this contract:\n\e[32m$branchNameRegExp\e[0m\n"
  echo -e "Your commit will be rejected. You should rename your branch to a valid name and try again.\n"
  exit 1
fi

# Guard for staged files linting (see "lint-staged" key in package.json)

npx --no-install lint-staged
